name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
          ssh-keyscan -t rsa kemboi.ddns.net > ~/.ssh/known_hosts
          echo "${{secrets.SERVER_PK}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ls -lhart ~/.ssh/id_rsa

      - run: npm install
      - run: npm run build

      - run: scp -r build/* brian@kemboi.ddns.net:/srv/www/react-github-actions/build/

      #     git remote add develop brian@kemboi.ddns.net:/srv/git/react-github-actions.git
      #     git remote add github git@github.com:BrianKemboi/react-github-actions.git

      #     git config --global user.name github-actions
      #     git config --global user.email actions@git.com

      # - run: git fetch --unshallow github develop
      # - run: git push develop develop:master